# Generated by Django 5.0 on 2023-12-18 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_alter_post_image_favorite'),
        ('users', '0003_alter_post_image_alter_profile_icon'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='favorite_posts',
            field=models.ManyToManyField(blank=True, related_name='favorited_by', to='posts.post'),
        ),
    ]
