# Generated by Django 5.0 on 2023-12-22 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_post_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='favorite_posts',
        ),
    ]
